name: Release Action
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Output version code
        run: echo BUILD_NUMBER=${{ github.run_number }} > ./version.properties

      - name: Build Project
        run: ./gradlew clean assembleDebug

      - name: Get apk name
        id: apk-name
        run: |
          APK_NAME=$(echo app/build/outputs/apk/debug/*.apk)
          echo "::set-output name=APK_NAME::${APK_NAME}"

      - name: Get bundle name
        id: bundle-name
        run: |
          BUNDLE_NAME=$(echo app/build/outputs/apk/debug/*.apk)
          echo "::set-output name=BUNDLE_NAME::${BUNDLE_NAME}"

      - name: Upload App bundle
        uses: actions/upload-artifact@v1
        with:
          name: debug-bundle
          path: ${{ steps.bundle-name.outputs.BUNDLE_NAME }}


  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
        
      - name: Verify gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: permission
        run: chmod +x ./gradlew
      - name: Detecting changes
        run: ./build_pull_request.sh

      - name: Run unit tests and Code Coverage
        if: env.build_commands != ''
        run: bash ./gradlew clean $build_commands

